### ISSUE TITLE
help: error on single page project

### ISSUE THREAD

**Issue by cesarbhering** [nuxt-modules/ionic#460] opened 2023-09-13 02:42 UTC
### 📚 What are you trying to do?

I'm trying ionic module for the first time, but i keep getting the error below:
`[nuxt] error caught during app initialization TypeError: Cannot read properties of undefined (reading 'beforeEach')`

I'm just deleting the **app.vue** file, and creating a **./pages/index.vue** file, that looks like this:

```js
<template>
  <ion-page>
   <h1>TEST</h1>
  </ion-page>
</template>

<script setup>
</script>

<style lang="scss" scoped>
</style>
```
What am i doing wrong ?

### 🔍 What have you tried?

Check for the error using "Pause on caught exceptions".

useRouter from nuxt3 is undefined.

![image](https://github.com/nuxt-modules/ionic/assets/59737309/acba2048-394d-4b13-a622-158f44cdcbea)

### ℹ️ Additional context

**nuxt.config.ts**

```js
export default defineNuxtConfig({
  devtools: { enabled: true },
  modules: ['@nuxtjs/ionic'],
  ssr: false,
})
```

**nvm current**
`v18.17.1`

**Comment by chrisspiegl** [comment] 2023-09-24 11:02
I think I ran into this issue as well.

Using `nuxt generate` to build a single page app.

having the ionic router set to be enabled in the `nuxt.config.js` file.

For me the error looks like this:

```
error caught during app initialization TypeError: Cannot read properties of undefined (reading 'beforeResolve')
    at setup (payload.client.js:14:5)
    at nuxt.js:109:60
………
```

**Comment by chrisspiegl** [comment] 2023-09-25 00:44
I just tried this in a completely new Nuxt Project for testing.

- Installed Nuxt
- Installed @nuxtjs/ionic
- Run `pnpm dev` works
- Run `pnpm generate` and then preview the `npx serve dist`:
	- does not work and throws above error with the `beforeResolve` not being found on undefined
- Disable the `router` via `ionic: { integrations: { router: false } }`
	- 	Now the generate + preview does work and load.

So, to me it feels like the issue is somewhere inside the ionic router integration.

**Comment by cesarbhering** [comment] 2023-10-04 01:46
Thanks alot @chrisspiegl !

**Comment by johannschopplich** [comment] 2023-10-04 08:45
@cesarbhering @chrisspiegl As a workaround, you have to disable payload extraction. With the following config applied, your app will work in the latest Nuxt version:

```ts

export default defineNuxtConfig({
  experimental: {
    // We have to disable payload extraction, or it will break the non-SSR build
    payloadExtraction: false,
  },
});
```

**Comment by chrisspiegl** [comment] 2023-10-04 09:48
Thank you for providing this insight and fix. I'll be testing it out in the next update of our dependencies.

**Comment by frankspee** [comment] 2023-12-27 10:33
Just to make people not run around checking issues, this issue is related: https://github.com/nuxt-modules/ionic/issues/484

**Comment by danielroe** [comment] 2024-01-09 11:17
resolved in https://github.com/nuxt-modules/ionic/commit/b35c6429a4b8da22ee25d8530373f65022ed55a8

**Closed by danielroe** 2024-01-09 11:17 UTC
