### ISSUE TITLE
Incorrect Warning on Nuxt 3.10

### ISSUE THREAD

**Issue by evanlegamer** [nuxt-modules/ionic#524] opened 2024-03-11 06:04 UTC
### 📚 What are you trying to do?

I'm just trying to use Ionic router. It's working correctly but I got an error.

![image](https://github.com/nuxt-modules/ionic/assets/18480367/38c9719f-37bc-4810-bee6-b9dfa50efcca)

### 🔍 What have you tried?

I tried to disable pages by putting in nuxt.config.js :

```js
pages: false
```

everything stop to work correctly, so the advice they give in the warning is incorrect also.

**Comment by CHIBX** [comment] 2024-03-26 08:39
> ### 📚 What are you trying to do?
> I'm just trying to use Ionic router. It's working correctly but I got an error.
> 
> ![image](https://private-user-images.githubusercontent.com/18480367/311600255-38c9719f-37bc-4810-bee6-b9dfa50efcca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NDI0NTMsIm5iZiI6MTcxMTQ0MjE1MywicGF0aCI6Ii8xODQ4MDM2Ny8zMTE2MDAyNTUtMzhjOTcxOWYtMzdiYy00ODEwLWJlZTYtYjlkZmE1MGVmY2NhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDA4MzU1M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwZTYxNWRmNWE0MzU1OTk2NTEzODc5ZmZmNjJjNTNiNzRiYTY4MmE0NTA1Y2I5NTFmZDJiZjE3NDllMTVjODcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._56CzHwMJf-jc5tN6bARQMW1zeNZwbH6QHWTe1oVG3o)
> 
> ### 🔍 What have you tried?
> I tried to disable pages by putting in nuxt.config.js :
> 
> ```js
> pages: false
> ```
> 
> everything stop to work correctly, so the advice they give in the warning is incorrect also.
> 
> ### ℹ️ Additional context
> _No response_

I tried it too, but I guess the problem is that maybe the Ionic Vue router wasn't made to work without page integration.
Worry not, I will look into it, and see if I can get something out of it, but for now try and work with pages: true

**Comment by CHIBX** [comment] 2024-03-26 08:57
@evanlegamer  I also noticed in the Vue Devtools that Nuxt wraps the base element with NuxtRoot to properly inject helper props which would help in a normal Nuxt 3 application. But when you use the NuxtLayout or NuxtPage in an Ionic app, then problem could start along the way. When you use NuxtLayout with IonRouterView, the browser console should show a warning that a provide() couldn't be found for an inject() in the IonRouterView component. Also, the other way around, if you don't provide the IonApp, then various Ionic default animation and features won't work well

**Comment by abarke** [comment] 2024-05-07 12:48
I got the same issue. See: https://github.com/nuxt/nuxt/issues/24912#issuecomment-2095436218

**Comment by danielroe** [comment] 2024-05-22 21:10
This is resolved in https://github.com/nuxt-modules/ionic/pull/560 and will be in the next release.

**Closed by danielroe** 2024-05-22 21:10 UTC
Labels: bug, needs reproduction
