### ISSUE TITLE
fix: ionic 7 tabs don't have any style even on playground

### ISSUE THREAD

**Issue by Tragio** [nuxt-modules/ionic#321] opened 2023-04-08 07:56 UTC
### 🐛 The bug

Hi 👋 

I was trying out the last version of Ionic, and I noticed that the tabs don't have any style. On my personal app, I also noticed some other quirks. I searched upstream, on the ionic framework git and couldn't find anyone talking about this, so I'm not sure where it's coming from.

There's a bunch of `class="undefined"`.

Playground picture:

![CleanShot 2023-04-08 at 08 55 21](https://user-images.githubusercontent.com/5109593/230710448-dabc4d18-598b-4c76-ac75-485ddc39642f.jpg)

### 🛠️ To reproduce

https://stackblitz.com/github/nuxt-modules/ionic/tree/main/playground

### 🌈 Expected behaviour

Tabs have style.

**Comment by therhenals** [comment] 2023-04-09 01:25
Hello, the same behavior occurs with ion-back-button.

**Comment by rvmourik** [comment] 2023-05-08 07:43
I can confirm this issue still exists, what @therhenals says is also correct. The second time you run the command they do get loaded. However when using `nuxt generate` the styles for tabs are not included in the entry.css file. Which results in styles missing in the end build and when you open this in the IOS simulator you also missing the specific styling. For instance the `.button-inner` specific styles are not included.

**Comment by rvmourik** [comment] 2023-05-08 07:58
> I can confirm this issue still exists, what @therhenals says is also correct. The second time you run the command they do get loaded. However when using `nuxt generate` the styles for tabs are not included in the entry.css file. Which results in styles missing in the end build and when you open this in the IOS simulator you also missing the specific styling. For instance the `.button-inner` specific styles are not included.

In addition to this, it looks like it is happening with more components. For debugging purposes I added a simple list component.

**This is in the browser**
<img width="497" alt="image" src="https://user-images.githubusercontent.com/6427451/236768539-6c559b86-adec-470c-b9eb-d39993c303c7.png">

**This is the IOS simulator**
<img width="403" alt="image" src="https://user-images.githubusercontent.com/6427451/236768673-e4d1a37c-729a-4400-a477-dc6063cdef81.png">

You see the missing styling, the issue that it runs through the header is because of the missing safe view settings. But I don't think that is related to this problem.

**Comment by tlebeitsuk** [comment] 2023-05-15 06:04
I'm having the same problem. I need to run "pnpm dev" a second time to get the tab bar to show.

**Comment by MarcusAngel** [comment] 2023-06-21 04:43
Following up on this, not a blocker but having to run dev twice is silly

**Comment by then3rdman** [comment] 2023-08-30 05:02
So for more context it seems that ALL css is missing when this occurs. Its also not consistent

**Comment by then3rdman** [comment] 2023-09-06 06:43
Some further investigation.

We have in development where the error comes up that the page is missing the ion-page tag and we are missing the css. 

We have noticed that it happens for me when the Vite client warmed up message appears after the Nitro built in ## message.

Works
```
✔ Nuxt DevTools is enabled v0.8.2 (experimental)                                                                                                  
ℹ Vite client warmed up in 2487ms                                                                                                                 
✔ Nitro built in 1270 ms   
```

Doesn't work
```
✔ Nuxt DevTools is enabled v0.8.2 (experimental)                                                                                                  
✔ Nitro built in 1237 ms                                                                                                                    
ℹ Vite client warmed up in 3189ms
```

**Comment by CernyMatej** [comment] 2023-10-31 08:23
Hi, are there any updates on this issue? Were you able to find a reasonable workaround?

**Comment by JoshDonnell** [comment] 2024-04-26 11:39
Just wanted to see if anyone has a fix for this, seems to remove all my styles when running **generate** which makes my app unuseable out side of local dev with the  **dev** command.

**Comment by danielroe** [comment] 2024-05-22 21:10
This is not now reproducible. Let me know if you encounter this with the next release and we can reopen.

**Closed by danielroe** 2024-05-22 21:10 UTC
Labels: bug

**Comment by jakubkoje** [comment] 2024-09-16 15:25
> This is not now reproducible. Let me know if you encounter this with the next release and we can reopen.

I encountered the same issue today, after uprgrading nuxt to latest version.
#616
